apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-online
commonLabels:
  xenzonegroup.com/environment: demo
bases:
  - ../../base
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: tavern
  path: affinity.patch.yaml
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: tavern
  path: ingress.patch.yaml
- target:
    version: v1
    kind: Service
    name: tavern-flow-through
  path: flow-through.patch.yaml
- target:
    version: v1
    kind: Service
    name: tavern-facade-flow
  path: facade-flow.patch.yaml
- target:
    version: v1
    kind: ConfigMap
    name: tavern-caba-config
  path: config-map.patch.yaml
